### ISSUE TITLE
Update develop-ms branch so that it's aligned with latest microservices patterns

### ISSUE THREAD

**Issue by ckittrell** [BroadleafCommerce/blc-paypal#48]
# Description/Context
Context from @nathandmoore via Slack:
"blc-paypal is for their v1 APIs. It’s likely what existing clients who migrate to Microservices will want to use since they will currently be using those APIs. blc-micro-paypal integrates with the v2 APIs, tho still needs subscription/billing integration. So I think we still want to keep blc-paypal up to date."

This module (`blc-paypal`) needs to be updated so that it is aligned with the latest expectations from PaymentGatewayCommon. Our overall expectation is that this will require refactoring to _how_ various pieces are structured, but that the underlying functionality can remain untouched.

# TODOs
- [x] Update the PaymentGatewayCommon dependency to use the latest version
  - [x] Possibly restructure pom.xml to match the latest dependency management patterns (see APS as an example)
- [x] Work through compilation & runtime issues
- [x] Ensure that the PaymentResponse's properties are sufficiently populated
  - [x] Pulling data from the PaymentRequest
  - [x] Any new properties that should be populated
- [x] Test integration to validate that everything works as expected

# Commerce Next JS Starter
- Branch: (https://github.com/BroadleafCommerce/commerce-nextjs-starter/tree/themes/paypal-checkout-v1)
